# Generated by Django 5.2.7 on 2025-11-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=100)),
                ('VaiTro', models.CharField(blank=True, choices=[('NV', 'Nhân Viên'), ('QL', 'Quản Lý'), ('VT', 'Văn Thư'), ('TP', 'Trưởng Phòng')], max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('SDT', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenPhongBan', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhanCongCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=100)),
                ('MoTa', models.TextField(max_length=250)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('HanChot', models.DateTimeField()),
                ('TrangThai', models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50)),
                ('NguoiGiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_giao', to='QLVB.nhanvien')),
                ('NguoiNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_duoc_giao', to='QLVB.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='NhatKyCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('ThaoTac', models.TextField()),
                ('TrangThai', models.CharField(choices=[('Chờ thông qua', 'CHỜ THÔNG QUA'), ('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50)),
                ('NguoiThucHien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.nhanvien')),
                ('PhanCong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhatky', to='QLVB.phancongcongviec')),
            ],
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='MaPhongBan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_viens', to='QLVB.phongban'),
        ),
        migrations.CreateModel(
            name='VanBanDen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoHieu', models.CharField(max_length=100)),
                ('TrichYeu', models.CharField(max_length=250)),
                ('LoaiVBDen', models.CharField(max_length=100)),
                ('DonViPhatHanh', models.CharField(max_length=250)),
                ('NgayBanHanh', models.DateTimeField(blank=True, null=True)),
                ('NgayDen', models.DateTimeField(blank=True, null=True)),
                ('NoiDung', models.CharField(blank=True, max_length=250, null=True)),
                ('YeuCauVBDi', models.IntegerField(default=0)),
                ('DoKhan', models.CharField(choices=[('KHAN', 'Khẩn'), ('BINH THUONG', 'Bình thường')], default='BINH THUONG', max_length=50)),
                ('DoMat', models.CharField(choices=[('MAT', 'Mật'), ('BINH THUONG', 'Bình thường')], default='BINH THUONG', max_length=50)),
                ('TrangThai', models.CharField(blank=True, max_length=255, null=True)),
                ('FileDinhKem', models.FileField(blank=True, upload_to='vanbanden/')),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.nhanvien')),
                ('MaPhongBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.phongban')),
            ],
        ),
        migrations.AddField(
            model_name='phancongcongviec',
            name='VanBanDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.CreateModel(
            name='VanBanDi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoHieu', models.CharField(max_length=50, unique=True)),
                ('NgayBanHanh', models.DateField(blank=True, null=True)),
                ('TrichYeu', models.CharField(max_length=500)),
                ('NoiDung', models.TextField()),
                ('LoaiVbDi', models.CharField(max_length=255)),
                ('DonViNhan', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('FileDinhKem', models.FileField(blank=True, upload_to='vanbandi/')),
                ('DoMat', models.CharField(blank=True, max_length=255, null=True)),
                ('DoKhan', models.CharField(blank=True, max_length=255, null=True)),
                ('TrangThai', models.CharField(blank=True, max_length=255, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('MaNhanVien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QLVB.nhanvien')),
                ('MaPhongBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.phongban')),
                ('MaVBDen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.TextField()),
                ('NoiDung', models.TextField(blank=True, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('DaDoc', models.BooleanField(default=False)),
                ('MaNhanVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.nhanvien')),
                ('MaVBDen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden')),
                ('MaVBDi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi')),
            ],
        ),
        migrations.AddField(
            model_name='phancongcongviec',
            name='VanBanDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
    ]
