# Generated by Django 5.2.7 on 2025-11-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraCuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tra cứu',
                'verbose_name_plural': 'Tra cứu',
                'permissions': [('tracuu_hethong', 'Tra cứu toàn hệ thống')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhatKyCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('ThaoTac', models.TextField(verbose_name='Thao tác')),
                ('TrangThai', models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀN')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhanCongCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('MoTa', models.TextField(max_length=500, verbose_name='Mô tả')),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('HanChot', models.DateTimeField(verbose_name='Hạn chót')),
                ('TrangThai', models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀN')], default='Chờ xét duyệt', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenPhongBan', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
            },
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('NoiDung', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('NgayTao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('DaDoc', models.BooleanField(default=False, verbose_name='Đã đọc')),
            ],
            options={
                'permissions': [('xem_thongbao', 'Xem thông báo')],
            },
        ),
        migrations.CreateModel(
            name='VanBanDen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoHieu', models.CharField(max_length=100, verbose_name='Số hiệu')),
                ('TrichYeu', models.CharField(max_length=250, verbose_name='Trích yếu')),
                ('LoaiVBDen', models.CharField(max_length=100, verbose_name='Loại văn bản')),
                ('DonViPhatHanh', models.CharField(max_length=250, verbose_name='Đơn vị phát hành')),
                ('NgayBanHanh', models.DateTimeField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('NgayDen', models.DateTimeField(blank=True, null=True, verbose_name='Ngày đến')),
                ('NoiDung', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nội dung tóm tắt')),
                ('DoKhan', models.CharField(choices=[('KHAN', 'Khẩn'), ('BINH THUONG', 'Bình thường'), ('HOA TOC', 'Hỏa tốc')], default='BINH THUONG', max_length=20)),
                ('DoMat', models.CharField(choices=[('MAT', 'Mật'), ('TOI MAT', 'Tối mật'), ('BINH THUONG', 'Bình thường')], default='BINH THUONG', max_length=20)),
                ('TrangThai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái')),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='vanbanden/')),
            ],
            options={
                'verbose_name': 'Văn bản đến',
                'verbose_name_plural': 'Văn bản đến',
                'permissions': [('tao_vanbanden', 'Tạo văn bản đến'), ('sua_vanbanden', 'Sửa văn bản đến'), ('xemchitiet_vanbanden', 'Xem chi tiết văn bản đến'), ('xemdanhsach_vanbanden', 'Xem danh sách văn bản đến'), ('phancong_vanbanden', 'Phân công nhân viên (văn bản đến)'), ('xetduyet_vanbanden', 'Xét duyệt văn bản đến'), ('capnhat_trangthai_cv_vbden', 'Cập nhật trạng thái công việc'), ('xem_nhatky_vanbanden', 'Xem nhật ký hoạt động văn bản đến')],
            },
        ),
        migrations.CreateModel(
            name='VanBanDi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoHieu', models.CharField(max_length=50, unique=True, verbose_name='Số hiệu')),
                ('NgayBanHanh', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('TrichYeu', models.CharField(max_length=500, verbose_name='Trích yếu')),
                ('NoiDung', models.TextField(verbose_name='Nội dung')),
                ('LoaiVbDi', models.CharField(max_length=255, verbose_name='Loại văn bản đi')),
                ('DonViNhan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đơn vị nhận')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email nhận')),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='vanbandi/')),
                ('DoMat', models.CharField(blank=True, choices=[('BINH THUONG', 'Bình thường'), ('MAT', 'Mật'), ('TOI MAT', 'Tối mật')], default='BINH THUONG', max_length=20, null=True)),
                ('DoKhan', models.CharField(blank=True, choices=[('BINH THUONG', 'Bình thường'), ('KHAN', 'Khẩn'), ('HOA TOC', 'Hỏa tốc')], default='BINH THUONG', max_length=20, null=True)),
                ('TrangThai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái')),
                ('NgayTao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Văn bản đi / dự thảo',
                'verbose_name_plural': 'Văn bản đi / dự thảo',
                'permissions': [('tao_vanbandi', 'Tạo văn bản đi'), ('sua_vanbandi', 'Sửa văn bản đi'), ('xemchitiet_vanbandi', 'Xem chi tiết văn bản đi'), ('xemdanhsach_vanbandi', 'Xem danh sách văn bản đi'), ('thongqua_vanbandi', 'Thông qua văn bản đi'), ('xetduyet_vanbandi', 'Xét duyệt văn bản đi'), ('phancong_vanbandi', 'Phân công nhân viên (văn bản đi)'), ('banhanh_vanbandi', 'Ban hành văn bản đi')],
            },
        ),
    ]
