# Generated by Django 5.2.7 on 2025-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(default='Chờ xét duyệt', max_length=50),
        ),
    ]
