# Generated by Django 5.2.7 on 2025-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='YeuCauVBDi',
            field=models.IntegerField(choices=[(0, 'Không yêu cầu'), (1, 'Có yêu cầu')], default=0),
        ),
    ]
