# Generated by Django 5.2.7 on 2025-10-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbandi',
            name='TrichYeu',
            field=models.CharField(max_length=500),
        ),
    ]
