# Generated by Django 4.2.8 on 2025-11-29 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QLVB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='MaPhongBan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.phongban'),
        ),
        migrations.AddField(
            model_name='vanbandi',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AddField(
            model_name='vanbanden',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vanbanden',
            name='MaPhongBan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.phongban'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AddField(
            model_name='thongbao',
            name='MaVBDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
        migrations.AddField(
            model_name='phancongcongviec',
            name='NguoiGiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_giao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phancongcongviec',
            name='NguoiNhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_duoc_giao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phancongcongviec',
            name='VanBanDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AddField(
            model_name='phancongcongviec',
            name='VanBanDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
        migrations.AddField(
            model_name='nhatkycongviec',
            name='NguoiThucHien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhatkycongviec',
            name='PhanCong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhatky', to='QLVB.phancongcongviec'),
        ),
    ]
