# Generated by Django 4.2.8 on 2025-11-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkycongviec',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AddField(
            model_name='nhatkycongviec',
            name='MaVBDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀNH'), ('Chờ thông qua', 'CHỜ THÔNG QUA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoHieu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(blank=True, default='Chờ thông qua', max_length=50, null=True),
        ),
    ]
