# Generated by Django 4.2.8 on 2025-11-11 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QLVB', '0002_alter_nhatkycongviec_nguoithuchien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='NguoiThucHien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='PhanCong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhatky', to='QLVB.phancongcongviec'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='MoTa',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='NguoiGiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_giao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='NguoiNhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_duoc_giao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='VanBanDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='VanBanDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaVBDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='TieuDe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='MaPhongBan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.phongban'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoKhan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoMat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoHieu',
            field=models.CharField(default='KHONG_SO', max_length=50, unique=True),
        ),
    ]
