# Generated by Django 5.2.7 on 2025-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0002_alter_vanbandi_trichyeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='HinhThucVanBan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
