# Generated by Django 4.2.8 on 2025-10-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0002_vanbanden_trangthai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanbanden',
            name='TrangThai',
        ),
    ]
