# Generated by Django 4.2.8 on 2025-11-26 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QLVB', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanden',
            name='NguoiNhanTrinhKy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanbanden_trinhky', to=settings.AUTH_USER_MODEL, verbose_name='Người Nhận Trình Ký'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='FileDinhKem',
            field=models.FileField(blank=True, null=True, upload_to='vanbanden/'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(blank=True, default='Chờ xét duyệt', max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='YeuCauVBDi',
            field=models.IntegerField(choices=[(0, 'Không yêu cầu'), (1, 'Có yêu cầu')], default=0),
        ),
    ]
