# Generated by Django 4.2.8 on 2025-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0003_vanbanden_nguoinhantrinhky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='NoiDung',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrichYeu',
            field=models.CharField(max_length=500),
        ),
    ]
