# Generated by Django 4.2.8 on 2025-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0003_remove_vanbanden_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
