# Generated by Django 4.2.8 on 2025-11-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0003_alter_nhatkycongviec_nguoithuchien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='PhongBan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QLVB.phongban'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoHieu',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
