# Generated by Django 5.2.7 on 2025-11-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0003_alter_nhatkycongviec_nguoithuchien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='MoTa',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], default='Chờ xét duyệt', max_length=50),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='TieuDe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='DoKhan',
            field=models.CharField(choices=[('KHAN', 'Khẩn'), ('BINH THUONG', 'Bình thường'), ('HOA TOC', 'Hỏa tốc')], default='BINH THUONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='DoMat',
            field=models.CharField(choices=[('MAT', 'Mật'), ('TOI MAT', 'Tối mật'), ('BINH THUONG', 'Bình thường')], default='BINH THUONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='FileDinhKem',
            field=models.FileField(blank=True, null=True, upload_to='vanbanden/'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoKhan',
            field=models.CharField(blank=True, choices=[('BINH THUONG', 'Bình thường'), ('KHAN', 'Khẩn'), ('HOA TOC', 'Hỏa tốc')], default='BINH THUONG', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoMat',
            field=models.CharField(blank=True, choices=[('BINH THUONG', 'Bình thường'), ('MAT', 'Mật'), ('TOI MAT', 'Tối mật')], default='BINH THUONG', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='FileDinhKem',
            field=models.FileField(blank=True, null=True, upload_to='vanbandi/'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
