# Generated by Django 4.2.8 on 2025-11-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0003_nhatkycongviec_mavbden_nhatkycongviec_mavbdi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='MaVBDen',
        ),
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='MaVBDi',
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoHieu',
            field=models.CharField(default='TEMP_VB_000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
