# Generated by Django 4.2.8 on 2025-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0004_alter_vanbanden_noidung_alter_vanbanden_trichyeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayBanHanh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayDen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
