# Generated by Django 4.2.8 on 2025-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0004_vanbandi_phongban_alter_vanbandi_sohieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='NgaySoanThao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
