# Generated by Django 4.2.8 on 2025-10-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0004_vanbanden_trangthai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhanvien',
            old_name='PhongBan',
            new_name='MaPhongBan',
        ),
    ]
