# Generated by Django 4.2.8 on 2025-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0005_rename_phongban_nhanvien_maphongban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayBanHanh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
