# Generated by Django 4.2.8 on 2025-12-07 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QLVB', '0005_alter_vanbanden_ngaybanhanh_alter_vanbanden_ngayden'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraCuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tra cứu',
                'verbose_name_plural': 'Tra cứu',
                'permissions': [('tracuu_hethong', 'Tra cứu toàn hệ thống')],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='phongban',
            options={'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='thongbao',
            options={'permissions': [('xem_thongbao', 'Xem thông báo')]},
        ),
        migrations.AlterModelOptions(
            name='vanbanden',
            options={'permissions': [('tao_vanbanden', 'Tạo văn bản đến'), ('sua_vanbanden', 'Sửa văn bản đến'), ('xemchitiet_vanbanden', 'Xem chi tiết văn bản đến'), ('xemdanhsach_vanbanden', 'Xem danh sách văn bản đến'), ('phancong_vanbanden', 'Phân công nhân viên (văn bản đến)'), ('xetduyet_vanbanden', 'Xét duyệt văn bản đến'), ('capnhat_trangthai_cv_vbden', 'Cập nhật trạng thái công việc'), ('xem_nhatky_vanbanden', 'Xem nhật ký hoạt động văn bản đến')], 'verbose_name': 'Văn bản đến', 'verbose_name_plural': 'Văn bản đến'},
        ),
        migrations.AlterModelOptions(
            name='vanbandi',
            options={'permissions': [('tao_vanbandi', 'Tạo văn bản đi'), ('sua_vanbandi', 'Sửa văn bản đi'), ('xemchitiet_vanbandi', 'Xem chi tiết văn bản đi'), ('xemdanhsach_vanbandi', 'Xem danh sách văn bản đi'), ('thongqua_vanbandi', 'Thông qua văn bản đi'), ('xetduyet_vanbandi', 'Xét duyệt văn bản đi'), ('phancong_vanbandi', 'Phân công nhân viên (văn bản đi)'), ('banhanh_vanbandi', 'Ban hành văn bản đi')], 'verbose_name': 'Văn bản đi / dự thảo', 'verbose_name_plural': 'Văn bản đi / dự thảo'},
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='NguoiThucHien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='ThaoTac',
            field=models.TextField(verbose_name='Thao tác'),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀN'), ('Đã ban hành', 'ĐÃ BAN HÀN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='HanChot',
            field=models.DateTimeField(verbose_name='Hạn chót'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='MoTa',
            field=models.TextField(max_length=500, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='NguoiGiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_giao', to=settings.AUTH_USER_MODEL, verbose_name='Người giao'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='NguoiNhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_nhan', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='TieuDe',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='DaDoc',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='NgayTao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='NoiDung',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='TieuDe',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='DonViPhatHanh',
            field=models.CharField(max_length=250, verbose_name='Đơn vị phát hành'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='LoaiVBDen',
            field=models.CharField(max_length=100, verbose_name='Loại văn bản'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tiếp nhận'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='MaPhongBan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QLVB.phongban', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayBanHanh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày ban hành'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayDen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đến'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nội dung tóm tắt'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='SoHieu',
            field=models.CharField(max_length=100, verbose_name='Số hiệu'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrichYeu',
            field=models.CharField(max_length=250, verbose_name='Trích yếu'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DonViNhan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đơn vị nhận'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Email nhận'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='LoaiVbDi',
            field=models.CharField(max_length=255, verbose_name='Loại văn bản đi'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người soạn thảo'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden', verbose_name='Văn bản đến liên quan'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='NgayBanHanh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày ban hành'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='NgayTao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='NoiDung',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoHieu',
            field=models.CharField(max_length=50, unique=True, verbose_name='Số hiệu'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrichYeu',
            field=models.CharField(max_length=500, verbose_name='Trích yếu'),
        ),
    ]
