# Generated by Django 4.2.8 on 2025-12-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0006_tracuu_alter_phongban_options_alter_thongbao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkycongviec',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhatky_vbden', to='QLVB.vanbanden'),
        ),
        migrations.AddField(
            model_name='nhatkycongviec',
            name='MaVBDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhatky_vbdi', to='QLVB.vanbandi'),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(blank=True, default='Chờ xét duyệt', max_length=50, null=True, verbose_name='Trạng thái'),
        ),
    ]
