# Generated by Django 4.2.8 on 2025-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0006_alter_vanbanden_ngaybanhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='NgayDen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
