# Generated by Django 4.2.8 on 2025-10-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0007_alter_vanbanden_ngayden_alter_vanbanden_noidung'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbandi',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='MaVBDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi'),
        ),
    ]
