# Generated by Django 4.2.8 on 2025-11-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0008_vanbandi_mavbden_alter_nhatkycongviec_mavbden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhatkycongviec',
            old_name='MaNhanVien',
            new_name='NguoiThucHien',
        ),
        migrations.RenameField(
            model_name='nhatkycongviec',
            old_name='NgayTao',
            new_name='ThoiGian',
        ),
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='HanChot',
        ),
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='MaVBDen',
        ),
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='MaVBDi',
        ),
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='MoTa',
        ),
        migrations.RemoveField(
            model_name='nhatkycongviec',
            name='TieuDe',
        ),
        migrations.AddField(
            model_name='vanbanden',
            name='NguoiNhanTrinhKy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vanbanden_trinhky', to='QLVB.nhanvien'),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50),
        ),
        migrations.CreateModel(
            name='PhanCongCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=100)),
                ('MoTa', models.TextField(max_length=250)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('HanChot', models.DateTimeField()),
                ('TrangThai', models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50)),
                ('NguoiGiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_giao', to='QLVB.nhanvien')),
                ('NguoiNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_cong_viec_duoc_giao', to='QLVB.nhanvien')),
                ('VanBanDen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbanden')),
                ('VanBanDi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QLVB.vanbandi')),
            ],
        ),
        migrations.AddField(
            model_name='nhatkycongviec',
            name='PhanCong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nhatky', to='QLVB.phancongcongviec'),
            preserve_default=False,
        ),
    ]
