# Generated by Django 5.2.7 on 2025-10-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0008_vanbandi_mavbden_alter_nhatkycongviec_mavbden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbandi',
            name='MaNhanVien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QLVB.nhanvien'),
        ),
    ]
