# Generated by Django 5.2.7 on 2025-11-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0009_alter_vanbandi_manhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='MoTa',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='TieuDe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='DoKhan',
            field=models.CharField(choices=[('KHAN', 'Khẩn'), ('BINH THUONG', 'Bình thường')], default='BINH THUONG', max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='DoMat',
            field=models.CharField(choices=[('MAT', 'Mật'), ('BINH THUONG', 'Bình thường')], default='BINH THUONG', max_length=50),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='FileDinhKem',
            field=models.FileField(blank=True, default='', upload_to='vanbanden/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoKhan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoMat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='FileDinhKem',
            field=models.FileField(blank=True, default='', upload_to='vanbandi/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
