# Generated by Django 4.2.8 on 2025-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0009_rename_manhanvien_nhatkycongviec_nguoithuchien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanbanden',
            name='SoHieu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='TrichYeu',
            field=models.CharField(max_length=500),
        ),
    ]
