# Generated by Django 4.2.8 on 2025-11-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vai_tro',
            field=models.CharField(blank=True, choices=[('NV', 'Nhân Viên'), ('QL', 'Quản Lý'), ('VT', 'Văn Thư'), ('TP', 'Trưởng Phòng'), ('GD', 'Giám Đốc')], max_length=2, null=True, verbose_name='Vai trò'),
        ),
    ]
