# Generated by Django 5.2.7 on 2025-11-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['ho_ten'], 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.AddField(
            model_name='user',
            name='ma_phong_ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_viens', to='QLVB.phongban', verbose_name='Phòng ban'),
        ),
        migrations.AddField(
            model_name='user',
            name='vai_tro',
            field=models.CharField(blank=True, choices=[('NV', 'Nhân Viên'), ('QL', 'Quản Lý'), ('VT', 'Văn Thư'), ('TP', 'Trưởng Phòng')], max_length=2, null=True, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sdt',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
