# Generated by Django 5.2.7 on 2025-11-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_ma_phong_ban_user_vai_tro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
    ]
