# Generated by Django 5.2.7 on 2025-11-06 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='NguoiThucHien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhatky_thuchien', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhatkycongviec',
            name='PhanCong',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nhatky', to='QLVB.phancongcongviec'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='MoTa',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='NguoiGiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phancong_giao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='NguoiNhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phancong_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='TrangThai',
            field=models.CharField(choices=[('Chờ xét duyệt', 'CHỜ XÉT DUYỆT'), ('Bị từ chối', 'BỊ TỪ CHỐI'), ('Chờ phân công', 'CHỜ PHÂN CÔNG'), ('Chờ xác nhận', 'CHỜ XÁC NHẬN'), ('Đang xử lý', 'ĐANG XỬ LÝ'), ('Hoàn thành', 'HOÀN THÀNH'), ('Chờ ban hành', 'CHỜ BAN HÀNH'), ('Đã ban hành', 'ĐÃ BAN HÀNH')], default='Chờ xác nhận', max_length=50),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='VanBanDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phancong', to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='VanBanDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phancong', to='QLVB.vanbandi'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thongbao_nhan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thongbao', to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='MaVBDi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thongbao', to='QLVB.vanbandi'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='TieuDe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanbanden_xuly', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vanbanden',
            name='MaPhongBan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanbanden', to='QLVB.phongban'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoKhan',
            field=models.CharField(blank=True, choices=[('KHAN', 'Khẩn'), ('BINH THUONG', 'Bình thường')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='DoMat',
            field=models.CharField(blank=True, choices=[('MAT', 'Mật'), ('BINH THUONG', 'Bình thường')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanbandi_tao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='MaVBDen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vanbandi_lienket', to='QLVB.vanbanden'),
        ),
        migrations.AlterField(
            model_name='vanbandi',
            name='SoHieu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
